# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_mu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# from PyQt5 import QtCore, QtGui, QtWidgets


# class Ui_Mu(object):
#     def setupUi(self, Mu):
#         Mu.setObjectName("Mu")
#         Mu.resize(400, 300)
#         self.image_label = QtWidgets.QLabel(Mu)
#         self.image_label.setGeometry(QtCore.QRect(50, 50, 400, 400))
#         self.image_label.setScaledContents(True)
#         self.image_label.setObjectName("image_label")
#         self.image = QtGui.QPixmap("explain/mu explanation.png")
#         self.image_label.setPixmap(self.image)

#         self.retranslateUi(Mu)
#         QtCore.QMetaObject.connectSlotsByName(Mu)

#     def retranslateUi(self, Mu):
#         _translate = QtCore.QCoreApplication.translate
#         Mu.setWindowTitle(_translate("Mu", "Form"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Mu = QtWidgets.QWidget()
#     ui = Ui_Mu()
#     ui.setupUi(Mu)
#     Mu.show()
#     sys.exit(app.exec_())


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mu(object):
    def setupUi(self, Acc):
        Acc.setObjectName("Acc")
        Acc.resize(600, 172)

        self.centralwidget = QtWidgets.QWidget(Acc)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setScaledContents(True)
        self.image_label.setObjectName("image_label")
        self.gridLayout.addWidget(self.image_label, 0, 0, 1, 1)
        Acc.setCentralWidget(self.centralwidget)

        self.image = QtGui.QPixmap("explain/mu explanation.png")
        self.image_label.setPixmap(self.image)

        self.retranslateUi(Acc)
        QtCore.QMetaObject.connectSlotsByName(Acc)

    def retranslateUi(self, Acc):
        _translate = QtCore.QCoreApplication.translate
        Acc.setWindowTitle(_translate("Acc", "Coefficiant of friction explanation"))

class Acc(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Mu()
        self.ui.setupUi(self)

    def resizeEvent(self, event):
        scaled_pixmap = self.ui.image.scaled(
            self.ui.image_label.size(), QtCore.Qt.KeepAspectRatio, 
            QtCore.Qt.SmoothTransformation)
        self.ui.image_label.setPixmap(scaled_pixmap)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Acc = Acc()
    Acc.show()
    sys.exit(app.exec_())